#!/bin/bash

platform=$(uname)
is_linux=false
is_macos=false
if [[ "$platform" == "Linux" ]]; then
  echo "Linux detected"
  is_linux=true
elif [[ "$platform" == "Darwin" ]]; then
  echo "MacOS detected"
  is_macos=true
fi

echo "Checking if ruby is installed in system"
# Check if Ruby is already installed
if command -v ruby >/dev/null 2>&1; then
	echo "Ruby found in the system"
else
  echo "Ruby not found! Installing..."
    if $is_linux; then
      sudo apt-get install ruby-full
    elif $is_macos; then
      brew install ruby
    fi
fi

if $is_linux; then
  echo "Installing simplydo"
  sudo wget -O /usr/bin/simplydo https://raw.githubusercontent.com/chanduollala/simplydo/main/simplydo
  sudo chmod +x /usr/bin/simplydo

elif $is_macos; then
  echo "Installing simplydo"

  SHELL_CONFIG_FILE=""

  # Check the default shell
  if [[ "$SHELL" == "/bin/bash" ]]; then
    SHELL_CONFIG_FILE="$HOME/.bash_profile"
  elif [[ "$SHELL" == "/bin/zsh" ]]; then
    SHELL_CONFIG_FILE="$HOME/.zshrc"
  elif [[ "$SHELL" == "/bin/sh" ]]; then
    SHELL_CONFIG_FILE="$HOME/.profile"
  else
    echo "Unsupported shell: $SHELL"
    exit 1
  fi

  # Create /usr/local/bin directory if it doesn't exist
  sudo mkdir -p /usr/local/bin


  # Download simplydo and make it executable
  sudo curl -o /usr/local/bin/simplydo https://raw.githubusercontent.com/chanduollala/simplydo/main/usr/bin/simplydo
  sudo chmod +x /usr/local/bin/simplydo

  # Add /usr/local/bin to the PATH in the appropriate shell config file
  echo 'export PATH="/usr/local/bin:$PATH"' >> "$SHELL_CONFIG_FILE"

  # Source the shell config file to apply changes
  source "$SHELL_CONFIG_FILE"


else
  echo "platform not supported"
fi

echo "Starting Simplydo server"
simplydo start
exit