#!/bin/bash

platform=$(uname)
is_linux=false
is_macos=false
if [[ "$platform" == "Linux" ]]; then
  echo "Linux detected"
  is_linux=true
elif [[ "$platform" == "Darwin" ]]; then
  echo "MacOS detected"
  is_macos=true
fi

echo "Checking if ruby is installed in system"
# Check if Ruby is already installed
if command -v ruby >/dev/null 2>&1; then
	echo "Ruby found in the system"
else
  echo "Ruby not found! Installing..."
    if $is_linux; then
      sudo apt-get install ruby-full
    elif $is_macos; then
      brew install ruby
    fi
fi

if $is_linux; then
  echo "Installing simplydo"
  sudo wget -O /usr/bin/simplydo https://raw.githubusercontent.com/chanduollala/simplydo/main/simplydo
  sudo chmod +x /usr/bin/simplydo

elif $is_macos; then
  echo "Installing simplydo"

  SHELL_CONFIG_FILE=""

  # Check the default shell
  if [[ "$SHELL" == "/bin/bash" ]]; then
    SHELL_CONFIG_FILE="$HOME/.bash_profile"
  elif [[ "$SHELL" == "/bin/zsh" ]]; then
    SHELL_CONFIG_FILE="$HOME/.zshrc"
  elif [[ "$SHELL" == "/bin/sh" ]]; then
    SHELL_CONFIG_FILE="$HOME/.profile"
  else
    echo "Unsupported shell: $SHELL"
    exit 1
  fi


  # Create the /usr/local/simplydo directory
  sudo mkdir -p /usr/local

  # Download the simplydo ZIP archive from GitHub
  sudo curl -L -o /usr/local/simplydo.zip https://github.com/chanduollala/simplydo/archive/main.zip

  # Extract the contents of the ZIP archive
  sudo unzip /usr/local/simplydo.zip -d /usr/local

  # Rename the extracted directory
  sudo mv /usr/local/simplydo-main /usr/local/simplydo

  # Change permissions of the simplydo directory
  sudo chmod -R 755 /usr/local/simplydo

  # Remove the ZIP archive
  sudo rm /usr/local/simplydo.zip





  sudo chmod +x /usr/local/simplydo/bin/simplydo


  # Add /usr/local/bin to the PATH in the appropriate shell config file
  echo 'export PATH="/usr/local/simplydo/bin:$PATH"' >> "$SHELL_CONFIG_FILE"

  # Source the shell config file to apply changes
  source "$SHELL_CONFIG_FILE"


else
  echo "platform not supported"
fi

echo "Starting Simplydo server"
simplydo start
exit