#!/bin/bash

platform=$(uname)
is_linux=false
is_macos=false
if [[ "$platform" == "Linux" ]]; then
  echo "Linux detected"
  is_linux=true
elif [[ "$platform" == "Darwin" ]]; then
  echo "MacOS detected"
  is_macos=true
fi


if $is_linux; then
  echo "Installing simplydo"
  sudo wget -O /usr/bin/simplydo https://raw.githubusercontent.com/chanduollala/simplydo/main/simplydo
  sudo chmod +x /usr/bin/simplydo

else
  echo "platform not supported"
fi

