#!/bin/bash

platform=$(uname)
is_linux=false
is_macos=false
if [[ "$platform" == "Linux" ]]; then
  echo "Linux detected"
  is_linux=true
elif [[ "$platform" == "Darwin" ]]; then
  echo "MacOS detected"
  is_macos=true
fi

echo "Checking if ruby is installed in system"
# Check if Ruby is already installed
if command -v ruby >/dev/null 2>&1; then
	echo "Ruby found in the system"
else
  echo "Ruby not found! Installing..."
    if $is_linux; then
      sudo apt-get install ruby-full
    elif $is_macos; then
      brew install ruby
    fi
fi

if $is_linux; then
  echo "Installing Raji"
  sudo wget -O /usr/bin/raji https://raw.githubusercontent.com/chanduollala/raji/main/raji
  sudo chmod +x /usr/bin/raji

elif $is_macos; then
  echo "Installing Raji"

  SHELL_CONFIG_FILE=""

  # Check the default shell
  if [[ "$SHELL" == "/bin/bash" ]]; then
    SHELL_CONFIG_FILE="$HOME/.bash_profile"
  elif [[ "$SHELL" == "/bin/zsh" ]]; then
    SHELL_CONFIG_FILE="$HOME/.zshrc"
  elif [[ "$SHELL" == "/bin/sh" ]]; then
    SHELL_CONFIG_FILE="$HOME/.profile"
  else
    echo "Unsupported shell: $SHELL"
    exit 1
  fi


  # Create the /usr/local/raji directory
  sudo mkdir -p /usr/local

  # Download the raji ZIP archive from GitHub
  sudo curl -L -o /usr/local/raji.zip https://github.com/chanduollala/raji/archive/main.zip

  # Extract the contents of the ZIP archive
  sudo unzip /usr/local/raji.zip -d /usr/local

  # Rename the extracted directory
  sudo mv /usr/local/raji-main /usr/local/raji

  # Change permissions of the raji directory
  sudo chmod -R 755 /usr/local/raji

  # Remove the ZIP archive
  sudo rm /usr/local/raji.zip

  sudo chmod +x /usr/local/raji/bin/raji


  # Add /usr/local/bin to the PATH in the appropriate shell config file
  echo 'export PATH="/usr/local/raji/bin:$PATH"' >> "$SHELL_CONFIG_FILE"

  # Source the shell config file to apply changes
  source "$SHELL_CONFIG_FILE"


else
  echo "platform not supported"
fi

echo "Starting Raji server"


if $is_linux; then
  raji start
elif $is_macos; then
  /usr/local/simplydo/bin/raji start
fi

exec shell
echo "Restart terminal"