#!/bin/bash

platform=$(uname)
is_linux=false
is_macos=false
if [[ "$platform" == "Linux" ]]; then
  echo "Linux detected"
  is_linux=true
elif [[ "$platform" == "Darwin" ]]; then
  echo "MacOS detected"
  is_macos=true
fi

read -p "Are you sure you want to uninstall simplydo? (y/n): " answer

if [[ $answer == "y" ]]; then
  if $is_linux; then
    echo "Uninstalling simplydo"


  elif $is_macos; then
    echo "Uninstalling simplydo"
    sudo rm -r usr/local/raji


  else
    echo "platform not supported"
  fi
else
  echo "Aborted."
fi



